// Package trees provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package trees

import (
	"time"
)

const (
	JWTAuthScopes = "JWTAuth.Scopes"
)

// Error defines model for Error.
type Error struct {
	Code    int32  `json:"code"`
	Message string `json:"message"`
}

// Tree defines model for Tree.
type Tree struct {
	Comment              *string        `json:"comment,omitempty"`
	CreateTime           time.Time      `json:"create_time"`
	Creator              int32          `json:"creator"`
	Description          *string        `json:"description,omitempty"`
	ExternalId           *int32         `json:"external_id,omitempty"`
	Geom                 string         `json:"geom"`
	Id                   int32          `json:"id"`
	IdValidator          *int32         `json:"id_validator,omitempty"`
	InactivationReason   *string        `json:"inactivation_reason,omitempty"`
	InactivationTime     *time.Time     `json:"inactivation_time,omitempty"`
	IsActive             bool           `json:"is_active"`
	IsValidated          *bool          `json:"is_validated,omitempty"`
	LastModificationTime *time.Time     `json:"last_modification_time,omitempty"`
	LastModificationUser *int32         `json:"last_modification_user,omitempty"`
	Name                 string         `json:"name"`
	TreeAttributes       TreeAttributes `json:"tree_attributes"`
}

// TreeAttributes defines model for TreeAttributes.
type TreeAttributes struct {
	Circonference           *int32  `json:"circonference,omitempty"`
	Entouragerem            *string `json:"entouragerem,omitempty"`
	Envracinairerem         *string `json:"envracinairerem,omitempty"`
	Etatsanitairerem        *string `json:"etatsanitairerem,omitempty"`
	Idchkentourage          *int32  `json:"idchkentourage,omitempty"`
	Idchkrevsurface         *int32  `json:"idchkrevsurface,omitempty"`
	Identourage             *int32  `json:"identourage,omitempty"`
	Idetatsanitairecouronne *int32  `json:"idetatsanitairecouronne,omitempty"`
	Idetatsanitairepied     *int32  `json:"idetatsanitairepied,omitempty"`
	Idetatsanitairetronc    *int32  `json:"idetatsanitairetronc,omitempty"`
	Idnote                  *int32  `json:"idnote,omitempty"`
	Idrevsurface            *int32  `json:"idrevsurface,omitempty"`
	Idtobechecked           *int32  `json:"idtobechecked,omitempty"`
	Idvalidation            int32   `json:"idvalidation"`
	Revsurfacerem           *string `json:"revsurfacerem,omitempty"`
}

// TreeList defines model for TreeList.
type TreeList struct {
	CreateTime  time.Time `json:"create_time"`
	Creator     int32     `json:"creator"`
	Description *string   `json:"description,omitempty"`
	ExternalId  *int32    `json:"external_id,omitempty"`
	Geom        string    `json:"geom"`
	Id          int32     `json:"id"`
	IsActive    bool      `json:"is_active"`
	Name        string    `json:"name"`
}

// ListParams defines parameters for List.
type ListParams struct {
	// Limit maximum number of results to return
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`

	// Offset number of rows to skip before beginning to return rows
	Offset *int32 `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateJSONRequestBody defines body for Create for application/json ContentType.
type CreateJSONRequestBody = Tree

// UpdateFormdataRequestBody defines body for Update for application/x-www-form-urlencoded ContentType.
type UpdateFormdataRequestBody = Tree
